use_default_settings: true

general:
  debug: false
  instance_name: "Local Research Engine"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "fi-FI"

server:
  secret_key: "ultrasecretkey"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Tracker URL remover'

outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
